//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InAndOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyShift
    {
        public int CompanyShiftId { get; set; }
        public int FK_CompanyID { get; set; }
        public int FK_ShiftID { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<bool> IsSet { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Shift Shift { get; set; }
    }
}
