//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InAndOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.users = new HashSet<user>();
            this.CompanyShifts = new HashSet<CompanyShift>();
            this.Employees = new HashSet<Employee>();
            this.SalaryDeductions = new HashSet<SalaryDeduction>();
        }
    
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public Nullable<int> SelfId { get; set; }
        public byte[] PictureUrl { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string ContactEmail { get; set; }
        public string Country { get; set; }
        public string OperatingSince { get; set; }
        public Nullable<int> NoOfEmployees { get; set; }
        public Nullable<int> NoOfBranches { get; set; }
        public string Description { get; set; }
        public string CreatedEmployersDesignation { get; set; }
        public string WebsiteURL { get; set; }
        public string ServiceProviding { get; set; }
        public string IDCardNumber { get; set; }
        public string TypeOfIndustry { get; set; }
        public string ContactPhoneNumber { get; set; }
        public Nullable<int> PackageType { get; set; }
        public Nullable<int> CreatedById { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<user> users { get; set; }
        public virtual ICollection<CompanyShift> CompanyShifts { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<SalaryDeduction> SalaryDeductions { get; set; }
    }
}
