//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InAndOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentUpload
    {
        public int DocumentUploadID { get; set; }
        public string DocumentName { get; set; }
        public string ContentType { get; set; }
        public byte[] DocumentEncode { get; set; }
    }
}
