//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InAndOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceReport
    {
        public int PerformanceReportID { get; set; }
        public Nullable<int> FK_EmpID { get; set; }
        public Nullable<int> FK_ReportTypeID { get; set; }
        public Nullable<int> FK_QuarterID { get; set; }
        public Nullable<int> FK_DocumentUploadID { get; set; }
        public Nullable<int> FK_ExpectationID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string notes { get; set; }
        public Nullable<int> year { get; set; }
    
        public virtual Expectation Expectation { get; set; }
        public virtual Quarter Quarter { get; set; }
        public virtual ReportType ReportType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
