//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InAndOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportType
    {
        public ReportType()
        {
            this.PerformanceReports = new HashSet<PerformanceReport>();
        }
    
        public int ReportTypeId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PerformanceReport> PerformanceReports { get; set; }
    }
}
