//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InAndOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryDeduction
    {
        public int SalaryDeductionID { get; set; }
        public int FK_CompanyID { get; set; }
        public Nullable<int> NoOfDays { get; set; }
        public Nullable<int> NoOfHalfDays { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
