//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InAndOut.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.Companies = new HashSet<Company>();
        }
    
        public int user_id { get; set; }
        public string name { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string contact { get; set; }
        public int type { get; set; }
        public Nullable<int> roleID { get; set; }
        public Nullable<int> FK_CompanyID { get; set; }
    
        public virtual role role { get; set; }
        public virtual ICollection<Company> Companies { get; set; }
        public virtual Company Company { get; set; }
    }
}
